# Introduction to tensors

In [2]:
import torch

Q1) show reshaping, viewing, stacking, squeezing, unsqueezing of tensors

In [3]:
a = torch.tensor([1,2,3,4,5,6])
print('before reshape : ',a)

a = a.reshape([3,2])
print('after reshape : ',a)

b = torch.tensor([1,2,3,4,5,6,7,8,9])
print('view: ' ,b.view(3,3))

c1= torch.tensor([1,2,3])
c2 = torch.tensor([4,5,6])
c = torch.stack((c1,c2), dim=0)
print('stack (dim 0): \n' ,c)

c = torch.stack((c1,c2), dim=1)
print('stack (dim 1): \n' ,c)


d1 = torch.randn(3,1,2,1,5)
d = torch.squeeze(d1)
print('d.size() = ',d.size())

e1 = torch.arange(8, dtype=torch.float)
print('e1 = ', e1)

e = torch.unsqueeze(e1, dim=0)
print('unsqueeze dim =0 :  ', e.size())

e = torch.unsqueeze(e1, dim=1)
print('unsqueeze dim =1 :  ', e.size())

before reshape :  tensor([1, 2, 3, 4, 5, 6])
after reshape :  tensor([[1, 2],
        [3, 4],
        [5, 6]])
view:  tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
stack (dim 0): 
 tensor([[1, 2, 3],
        [4, 5, 6]])
stack (dim 1): 
 tensor([[1, 4],
        [2, 5],
        [3, 6]])
d.size() =  torch.Size([3, 2, 5])
e1 =  tensor([0., 1., 2., 3., 4., 5., 6., 7.])
unsqueeze dim =0 :   torch.Size([1, 8])
unsqueeze dim =1 :   torch.Size([8, 1])


Q2) show torch.permute()

In [4]:
# creating a tensor with random
# values of dimension 3 X 5 X 2
input_var = torch.randn(3, 5, 2)

# print size
print(input_var.size())

print(input_var)

# dimensions permuted
input_var = input_var.permute(2, 0, 1)

# print size
print(input_var.size())

print(input_var)

torch.Size([3, 5, 2])
tensor([[[ 0.2291, -0.2878],
         [-0.7506, -0.5217],
         [-0.6628,  0.0643],
         [-0.5715,  0.2028],
         [ 0.3270, -0.1267]],

        [[-0.0934, -0.9500],
         [-1.0053, -1.3176],
         [ 1.4736, -0.5063],
         [ 1.2469, -0.0294],
         [-1.2344, -0.3839]],

        [[-0.9872, -1.3017],
         [-0.7518,  0.0938],
         [-1.4954, -1.0144],
         [-0.0439, -1.4929],
         [ 0.0075, -0.5814]]])
torch.Size([2, 3, 5])
tensor([[[ 0.2291, -0.7506, -0.6628, -0.5715,  0.3270],
         [-0.0934, -1.0053,  1.4736,  1.2469, -1.2344],
         [-0.9872, -0.7518, -1.4954, -0.0439,  0.0075]],

        [[-0.2878, -0.5217,  0.0643,  0.2028, -0.1267],
         [-0.9500, -1.3176, -0.5063, -0.0294, -0.3839],
         [-1.3017,  0.0938, -1.0144, -1.4929, -0.5814]]])


Q3) indexing in tensors

In [5]:
tensor = torch.tensor([[1,5,3],[8,9,2]])
print(tensor)

print('at 1,0 = ' ,tensor[1,0])
print('at 1 = ' ,tensor[1])

tensor([[1, 5, 3],
        [8, 9, 2]])
at 1,0 =  tensor(8)
at 1 =  tensor([8, 9, 2])


Q4) convert numpy arrays to tensors and back to nparray

In [6]:
import numpy as np

npx = np.array([[1,2,3],[5,6,6], [7,8,9]])
print(npx, type(npx))

# change to tensor
t = torch.from_numpy(npx)

print(t, type(t))

npy = t.numpy()

print(npy, type(npy))

[[1 2 3]
 [5 6 6]
 [7 8 9]] <class 'numpy.ndarray'>
tensor([[1, 2, 3],
        [5, 6, 6],
        [7, 8, 9]]) <class 'torch.Tensor'>
[[1 2 3]
 [5 6 6]
 [7 8 9]] <class 'numpy.ndarray'>


Q5) create random tensor with shape (7,7)

In [7]:
random_tensor = torch.rand(7,7)

print(random_tensor, random_tensor.shape)

tensor([[0.3487, 0.4905, 0.9439, 0.4420, 0.6779, 0.1685, 0.1182],
        [0.7538, 0.4243, 0.3901, 0.3188, 0.6473, 0.9623, 0.0432],
        [0.5590, 0.7300, 0.4295, 0.4529, 0.9965, 0.5801, 0.7019],
        [0.6497, 0.4312, 0.5624, 0.6565, 0.4955, 0.6429, 0.6534],
        [0.5343, 0.9188, 0.7224, 0.5305, 0.5001, 0.2636, 0.3235],
        [0.1955, 0.1141, 0.2439, 0.9150, 0.9301, 0.9747, 0.5452],
        [0.7967, 0.9431, 0.3031, 0.0012, 0.1456, 0.2860, 0.5604]]) torch.Size([7, 7])


Q6) Perform matrix multiplication

In [24]:
print(random_tensor)

random_tensor2 = torch.rand(1,7)
print(random_tensor2)

random_tensor2 = torch.transpose(random_tensor2, 0, 1)
print(random_tensor2)

mult = torch.mm(random_tensor, random_tensor2)

print("Final matrix after multiplication: \n",mult)

tensor([[0.3487, 0.4905, 0.9439, 0.4420, 0.6779, 0.1685, 0.1182],
        [0.7538, 0.4243, 0.3901, 0.3188, 0.6473, 0.9623, 0.0432],
        [0.5590, 0.7300, 0.4295, 0.4529, 0.9965, 0.5801, 0.7019],
        [0.6497, 0.4312, 0.5624, 0.6565, 0.4955, 0.6429, 0.6534],
        [0.5343, 0.9188, 0.7224, 0.5305, 0.5001, 0.2636, 0.3235],
        [0.1955, 0.1141, 0.2439, 0.9150, 0.9301, 0.9747, 0.5452],
        [0.7967, 0.9431, 0.3031, 0.0012, 0.1456, 0.2860, 0.5604]])
tensor([[0.5866, 0.9828, 0.7399, 0.3641, 0.0116, 0.4782, 0.5684]])
tensor([[0.5866],
        [0.9828],
        [0.7399],
        [0.3641],
        [0.0116],
        [0.4782],
        [0.5684]])
Final matrix after multiplication: 
 tensor([[1.7015],
        [1.7561],
        [2.2159],
        [2.1445],
        [2.2598],
        [1.5271],
        [2.0758]])


Q7) create two random tensors of shape (2,3) and send them both to GPU

In [8]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print('a.device = ',a.device)
print('b.device = ',b.device)

# send to gpu
print(torch.cuda.is_available())

if torch.cuda.is_available():
   a = a.cuda()
   b = b.cuda()

print('a.device = ',a.device)
print('b.device = ',b.device)

a.device =  cpu
b.device =  cpu
True
a.device =  cuda:0
b.device =  cuda:0
