# Introduction to Tensors

In [2]:
import torch

In [6]:
x = torch.rand(3, requires_grad = True)
x

tensor([0.9640, 0.0183, 0.9013], requires_grad=True)

### Solved Examples

Solved example 1

In [9]:
#setting up a simple graph relating x, y, z
x = torch.tensor(3.5, requires_grad = True)

#equations
y = x**2
z = 2*y + 3

#values of each variable
print("x: ",x)
print("y: ",y)
print("z: ",z)

#gradients:
z.backward()
print("grad of dz/dx at x = 3.5: ", x.grad.item())

x:  tensor(3.5000, requires_grad=True)
y:  tensor(12.2500, grad_fn=<PowBackward0>)
z:  tensor(27.5000, grad_fn=<AddBackward0>)
grad of dz/dx at x = 3.5:  14.0


    Solved example 2

In [10]:
def f(x):
    return (x-2)**2
def fp(x):
    return 2*(x-2)

x = torch.tensor([1.0], requires_grad = True)
y = f(x)
y.backward()

print('Analytical f\'(x): ',fp(x))
print('Pytorch f\'(x):',x.grad)

Analytical f'(x):  tensor([-2.], grad_fn=<MulBackward0>)
Pytorch f'(x): tensor([-2.])


Solved example 3

In [11]:
x = torch.tensor([2.0])
x.requires_grad_(True)
print(x)

y = x**2 + 5
print(y)

a_grad = 2*x

y.backward()
print("Analytical grad: ", a_grad)
print("Pytorch grad: :", x.grad)

tensor([2.], requires_grad=True)
tensor([9.], grad_fn=<AddBackward0>)
Analytical grad:  tensor([4.], grad_fn=<MulBackward0>)
Pytorch grad: : tensor([4.])


### Exercise questions

Q1)

In [15]:
a = torch.tensor([1.0], requires_grad = True)
b = torch.tensor([3.0], requires_grad = True)

x = 2*a + 3* b
y = 5*a**2 + 3*b**3
z = 2*x + 3*y

z.backward()
print("PyTorch: ")
print("dz/da = ", a.grad)
print("dz/db = ", b.grad)

print("\nAnalytical: ")
dzdx = 2
dzdy = 3
dxda = 2
dyda = 10*a

dzda = dzdx * dxda + dzdy * dyda
print("dz/da = ", dzda)

PyTorch: 
dz/da =  tensor([34.])
dz/db =  tensor([249.])

Analytical: 
dz/da =  tensor([34.], grad_fn=<AddBackward0>)


Q2)

In [16]:
b = torch.tensor([1.0])
x = torch.tensor([2.0])
w = torch.tensor([3.0], requires_grad = True)

u = w*x
v = u + b
a = torch.relu(v)

a.backward()
print("Pytorch grad: ", w.grad)

Pytorch grad:  tensor([2.])


Q3)

In [18]:
b = torch.tensor([1.0])
x = torch.tensor([2.0])
w = torch.tensor([3.0], requires_grad = True)

u = w*x
v = u + b
a = torch.sigmoid(v)

a.backward()
print("Pytorch grad: ", w.grad)

Pytorch grad:  tensor([0.0018])


Q4)

In [20]:
x = torch.tensor([1.0], requires_grad = True)

f = torch.exp(-x**2 - 2*x - torch.sin(x))
f.backward()

print("grad: ", x.grad)

x = torch.tensor([1.0], requires_grad = True)

a = x**2
b = 2*x
c = torch.sin(x)

f = torch.exp(-a - b - c)
f.backward()

print("grad: ", x.grad)

grad:  tensor([-0.0974])
grad:  tensor([-0.0974])


Q5)

In [22]:
x = torch.tensor([2.0], requires_grad = True)

a = 8*x**4
b = 3*x**3
c = 7*x**2
d = 6*x

y = a+b+c+d+3

y.backward()
print("grad: ", x.grad)

grad:  tensor([326.])


Q6)

In [23]:
x = torch.tensor([1.0], requires_grad = True)
y = torch.tensor([2.0], requires_grad = True)
z = torch.tensor([3.0], requires_grad = True)

a = 2*x
b = torch.sin(y)
c = a/b
d = c*z
e = torch.log(d+1)
f = torch.tanh(e)

f.backward()

print("df/dx: ", x.grad)
print("df/dy: ", y.grad)
print("df/dz: ", z.grad)

df/dx:  tensor([0.0581])
df/dy:  tensor([0.0266])
df/dz:  tensor([0.0194])
